require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__
]).strip

platform :ios, '15.1'
prepare_react_native_project!

def plugin_pods
  use_frameworks!
  use_react_native!(
    :path => '../node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'SSZipArchive', '2.4.3'
  pod 'Alamofire', '5.10.2'
  pod 'Version', '0.8.0'
  pod 'BigInt', '5.2.0'
end

target 'Plugin' do
  plugin_pods
end

target 'PluginTests' do
  use_frameworks!
  inherit! :complete
end

post_install do |installer|
  react_native_post_install(
    installer,
    '../node_modules/react-native',
    :mac_catalyst_enabled => true
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end
  end
end
