/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package com.codepushgo.reactnativeupdater;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Build;
import android.util.Log;
import androidx.annotation.NonNull;
import com.facebook.react.bridge.ReactApplicationContext;
import io.github.g00fy2.versioncompare.Version;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.IOException;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeUnit;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import okhttp3.*;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class ReactNativeUpdaterCore {

  private static final String AB =
    "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  private static final SecureRandom rnd = new SecureRandom();

  private static final String INFO_SUFFIX = "_info";

  private static final String FALLBACK_VERSION = "pastVersion";
  private static final String NEXT_VERSION = "nextVersion";
  private static final String bundleDirectory = "versions";

  public static final String TAG = "ReactNative-updater";
  public SharedPreferences.Editor editor;
  public SharedPreferences prefs;

  public OkHttpClient client;

  public File documentsDir;
  public Boolean directUpdate = false;
  private final ReactApplicationContext reactContext;
  public String PLUGIN_VERSION = "";
  public String versionBuild = "";
  public String versionCode = "";
  public String versionOs = "";

  public String customId = "";
  public String statsUrl = "";
  public String channelUrl = "";
  public String defaultChannel = "";
  public String appId = "";
  public String publicKey = "";
  public String deviceID = "";
  public int timeout = 20000;

  private final FilenameFilter filter = (f, name) -> {
    // ignore directories generated by mac os x
    return (
      !name.startsWith("__MACOSX") &&
      !name.startsWith(".") &&
      !name.startsWith(".DS_Store")
    );
  };

  public ReactNativeUpdaterCore(ReactApplicationContext context) {
    this.reactContext = context;
    this.documentsDir = this.reactContext.getFilesDir();
    this.client = new OkHttpClient.Builder()
      .protocols(Arrays.asList(Protocol.HTTP_2, Protocol.HTTP_1_1))
      .connectTimeout(this.timeout, TimeUnit.MILLISECONDS)
      .readTimeout(this.timeout, TimeUnit.MILLISECONDS)
      .writeTimeout(this.timeout, TimeUnit.MILLISECONDS)
      .build();
    this.versionOs = Build.VERSION.RELEASE;
  }

  private boolean isProd() {
    try {
      return !Objects.requireNonNull(getClass().getPackage())
        .getName()
        .contains(".debug");
    } catch (Exception e) {
      return true; // Default to production if we can't determine
    }
  }

  private boolean isEmulator() {
    return (
      (Build.BRAND.startsWith("generic") &&
        Build.DEVICE.startsWith("generic")) ||
      Build.FINGERPRINT.startsWith("generic") ||
      Build.FINGERPRINT.startsWith("unknown") ||
      Build.HARDWARE.contains("goldfish") ||
      Build.HARDWARE.contains("ranchu") ||
      Build.MODEL.contains("google_sdk") ||
      Build.MODEL.contains("Emulator") ||
      Build.MODEL.contains("Android SDK built for x86") ||
      Build.MANUFACTURER.contains("Genymotion") ||
      Build.PRODUCT.contains("sdk_google") ||
      Build.PRODUCT.contains("google_sdk") ||
      Build.PRODUCT.contains("sdk") ||
      Build.PRODUCT.contains("sdk_x86") ||
      Build.PRODUCT.contains("sdk_gphone64_arm64") ||
      Build.PRODUCT.contains("vbox86p") ||
      Build.PRODUCT.contains("emulator") ||
      Build.PRODUCT.contains("simulator")
    );
  }

  private int calcTotalPercent(
    final int percent,
    final int min,
    final int max
  ) {
    return (percent * (max - min)) / 100 + min;
  }

  void notifyDownload(final String id, final int percent) {}

  void directUpdateFinish(final BundleInfo latest) {}

  void notifyListeners(final String id, final JSONObject res) {}

  public String randomString() {
    final StringBuilder sb = new StringBuilder(10);
    for (int i = 0; i < 10; i++) sb.append(AB.charAt(rnd.nextInt(AB.length())));
    return sb.toString();
  }

  private File unzip(final String id, final File zipFile, final String dest)
    throws IOException {
    final File targetDirectory = new File(this.documentsDir, dest);
    try (
      final BufferedInputStream bis = new BufferedInputStream(
        new FileInputStream(zipFile)
      );
      final ZipInputStream zis = new ZipInputStream(bis)
    ) {
      int count;
      final int bufferSize = 8192;
      final byte[] buffer = new byte[bufferSize];
      final long lengthTotal = zipFile.length();
      long lengthRead = bufferSize;
      int percent = 0;
      this.notifyDownload(id, 75);

      ZipEntry entry;
      while ((entry = zis.getNextEntry()) != null) {
        if (entry.getName().contains("\\")) {
          Log.e(
            TAG,
            "unzip: Windows path is not supported, please use unix path as require by zip RFC: " +
            entry.getName()
          );
          this.sendStats("windows_path_fail");
        }
        final File file = new File(targetDirectory, entry.getName());
        final String canonicalPath = file.getCanonicalPath();
        final String canonicalDir = targetDirectory.getCanonicalPath();
        final File dir = entry.isDirectory() ? file : file.getParentFile();

        if (!canonicalPath.startsWith(canonicalDir)) {
          this.sendStats("canonical_path_fail");
          throw new FileNotFoundException(
            "SecurityException, Failed to ensure directory is the start path : " +
            canonicalDir +
            " of " +
            canonicalPath
          );
        }

        assert dir != null;
        if (!dir.isDirectory() && !dir.mkdirs()) {
          this.sendStats("directory_path_fail");
          throw new FileNotFoundException(
            "Failed to ensure directory: " + dir.getAbsolutePath()
          );
        }

        if (entry.isDirectory()) {
          continue;
        }

        try (final FileOutputStream outputStream = new FileOutputStream(file)) {
          while ((count = zis.read(buffer)) != -1) outputStream.write(
            buffer,
            0,
            count
          );
        }

        final int newPercent = (int) ((lengthRead / (float) lengthTotal) * 100);
        if (lengthTotal > 1 && newPercent != percent) {
          percent = newPercent;
          this.notifyDownload(id, this.calcTotalPercent(percent, 75, 90));
        }

        lengthRead += entry.getCompressedSize();
      }
      return targetDirectory;
    } catch (IOException e) {
      this.sendStats("unzip_fail");
      throw new IOException("Failed to unzip: " + zipFile.getPath());
    }
  }

  private void flattenAssets(final File sourceFile, final String dest)
    throws IOException {
    if (!sourceFile.exists()) {
      throw new FileNotFoundException(
        "Source file not found: " + sourceFile.getPath()
      );
    }
    final File destinationFile = new File(this.documentsDir, dest);
    Objects.requireNonNull(destinationFile.getParentFile()).mkdirs();
    final String[] entries = sourceFile.list(this.filter);
    if (entries == null || entries.length == 0) {
      throw new IOException(
        "Source file was not a directory or was empty: " + sourceFile.getPath()
      );
    }
    if (entries.length == 1 && !"index.html".equals(entries[0])) {
      final File child = new File(sourceFile, entries[0]);
      if (child.isDirectory()) {
        child.renameTo(destinationFile);
      } else {
        if (!destinationFile.exists() && !destinationFile.mkdirs()) {
          throw new IOException(
            "Failed to create destination directory: " +
            destinationFile.getPath()
          );
        }
        File movedFile = new File(destinationFile, child.getName());
        if (!child.renameTo(movedFile)) {
          throw new IOException(
            "Failed to move file into destination: " + child.getPath()
          );
        }
      }
    } else {
      sourceFile.renameTo(destinationFile);
    }
    sourceFile.delete();
  }

  private void download(
    final String id,
    final String url,
    final String dest,
    final String version,
    final String sessionKey,
    final String checksum,
    final JSONArray manifest
  ) {
    Context context = this.reactContext;
    if (context == null) {
      Log.e(TAG, "Context is null, cannot enqueue download");
      return;
    }
    DownloadWorkerManager.enqueueDownload(
      context,
      url,
      id,
      this.documentsDir.getAbsolutePath(),
      dest,
      version,
      sessionKey,
      checksum,
      this.publicKey,
      manifest != null
    );
    if (manifest != null) {
      DataManager.getInstance().setManifest(manifest);
    }
  }

  public Boolean finishDownload(
    String id,
    String dest,
    String version,
    String sessionKey,
    String checksumRes,
    Boolean setNext,
    Boolean isManifest
  ) {
    File downloaded = null;
    String checksum = "";

    try {
      downloaded = new File(this.documentsDir, dest);

      if (!isManifest) {
        String checksumDecrypted = Objects.requireNonNullElse(checksumRes, "");
        if (!sessionKey.isEmpty()) {
          CryptoCipherV2.decryptFile(downloaded, publicKey, sessionKey);
          checksumDecrypted = CryptoCipherV2.decryptChecksum(
            checksumRes,
            publicKey
          );
          checksum = CryptoCipherV2.calcChecksum(downloaded);
        } else {
          checksum = CryptoCipherV2.calcChecksum(downloaded);
        }
        if (
          (!checksumDecrypted.isEmpty() || !this.publicKey.isEmpty()) &&
          !checksumDecrypted.equals(checksum)
        ) {
          Log.e(
            ReactNativeUpdaterCore.TAG,
            "Error checksum '" + checksumDecrypted + "' '" + checksum + "' '"
          );
          this.sendStats("checksum_fail");
          throw new IOException("Checksum failed: " + id);
        }
      }
    } catch (Exception e) {
      this.delete(id);
      this.sendStats("download_fail");
      Log.e(TAG, "finishDownload failed - checksum/decrypt", e);
      return false;
    }

    try {
      if (!isManifest) {
        final File unzipped = this.unzip(id, downloaded, this.randomString());
        final String idName = bundleDirectory + "/" + id;
        this.flattenAssets(unzipped, idName);
      } else {
        final String idName = bundleDirectory + "/" + id;
        this.flattenAssets(downloaded, idName);
        if (downloaded != null) downloaded.delete();
      }
      this.saveBundleInfo(id, null);
      BundleInfo next = new BundleInfo(
        id,
        version,
        BundleStatus.PENDING,
        new Date(System.currentTimeMillis()),
        checksum
      );
      this.saveBundleInfo(id, next);

      if (setNext) {
        if (this.directUpdate) {
          this.setNextBundle(next.getId());
          this.directUpdate = false;
        } else {
          this.setNextBundle(next.getId());
        }
      }
      return true;
    } catch (IOException e) {
      e.printStackTrace();
      this.sendStats("download_fail");
      this.delete(id);
      Log.e(TAG, "finishDownload failed - unzip/flatten", e);
      return false;
    }
  }

  private void deleteDirectory(final File file) throws IOException {
    if (file.isDirectory()) {
      final File[] entries = file.listFiles();
      if (entries != null) {
        for (final File entry : entries) {
          this.deleteDirectory(entry);
        }
      }
    }
    if (!file.delete()) {
      throw new IOException("Failed to delete: " + file);
    }
  }

  public String downloadBackground(
    final String url,
    final String version,
    final String sessionKey,
    final String checksum,
    final JSONArray manifest
  ) {
    final String id = this.randomString();

    if (
      this.reactContext != null &&
      DownloadWorkerManager.isVersionDownloading(version)
    ) {
      Log.i(TAG, "Version already downloading: " + version);
      return null;
    }

    this.saveBundleInfo(
        id,
        new BundleInfo(
          id,
          version,
          BundleStatus.DOWNLOADING,
          new Date(System.currentTimeMillis()),
          ""
        )
      );
    this.download(
        id,
        url,
        this.randomString(),
        version,
        sessionKey,
        checksum,
        manifest
      );
    return id;
  }

  public BundleInfo download(
    final String url,
    final String version,
    final String sessionKey,
    final String checksum
  ) throws IOException {
    final String id = this.randomString();
    this.saveBundleInfo(
        id,
        new BundleInfo(
          id,
          version,
          BundleStatus.DOWNLOADING,
          new Date(System.currentTimeMillis()),
          ""
        )
      );
    this.download(
        id,
        url,
        this.randomString(),
        version,
        sessionKey,
        checksum,
        null
      );
    return getBundleInfo(id);
  }

  public List<BundleInfo> list(boolean rawList) {
    if (!rawList) {
      final List<BundleInfo> res = new ArrayList<>();
      final File destHot = new File(this.documentsDir, bundleDirectory);
      Log.d(TAG, "list File : " + destHot.getPath());
      if (destHot.exists()) {
        for (final File i : Objects.requireNonNull(destHot.listFiles())) {
          final String id = i.getName();
          res.add(this.getBundleInfo(id));
        }
      } else {
        Log.i(TAG, "No versions available to list" + destHot);
      }
      return res;
    } else {
      final List<BundleInfo> res = new ArrayList<>();
      for (String value : this.prefs.getAll().keySet()) {
        if (!value.matches("^[0-9A-Za-z]{10}_info$")) {
          continue;
        }

        res.add(this.getBundleInfo(value.split("_")[0]));
      }
      return res;
    }
  }

  public Boolean delete(final String id, final Boolean removeInfo)
    throws IOException {
    final BundleInfo deleted = this.getBundleInfo(id);
    if (deleted.isBuiltin() || this.getCurrentBundleId().equals(id)) {
      Log.e(TAG, "Cannot delete " + id);
      return false;
    }
    final BundleInfo next = this.getNextBundle();
    if (
      next != null &&
      !next.isDeleted() &&
      !next.isErrorStatus() &&
      next.getId().equals(id)
    ) {
      Log.e(TAG, "Cannot delete the next bundle" + id);
      return false;
    }
    if (this.reactContext != null) {
      DownloadWorkerManager.cancelVersionDownload(
        this.reactContext,
        deleted.getVersionName()
      );
    }
    final File bundle = new File(this.documentsDir, bundleDirectory + "/" + id);
    if (bundle.exists()) {
      this.deleteDirectory(bundle);
      if (!removeInfo) {
        this.saveBundleInfo(id, deleted.setStatus(BundleStatus.DELETED));
      } else {
        this.removeBundleInfo(id);
      }
      return true;
    }
    Log.e(TAG, "bundle removed: " + deleted.getVersionName());
    if (removeInfo) {
      this.removeBundleInfo(id);
    }
    this.sendStats("delete", deleted.getVersionName());
    return false;
  }

  public Boolean delete(final String id) {
    try {
      return this.delete(id, true);
    } catch (IOException e) {
      e.printStackTrace();
      Log.i(
        ReactNativeUpdaterCore.TAG,
        "Failed to delete bundle (" + id + ")" + "\nError:\n" + e.toString()
      );
      return false;
    }
  }

  public File getBundleDirectory(final String id) {
    return new File(this.documentsDir, bundleDirectory + "/" + id);
  }

  private boolean bundleExists(final String id) {
    final File bundle = this.getBundleDirectory(id);
    final BundleInfo bundleInfo = this.getBundleInfo(id);
    if (!bundle.exists() || !bundle.isDirectory() || bundleInfo.isDeleted()) {
      return false;
    }

    File htmlBundle = new File(bundle, "index.html");
    File rnAndroidBundle = new File(bundle, "index.android.bundle");
    File rnMainBundle = new File(bundle, "main.jsbundle");
    if (
      htmlBundle.exists() || rnAndroidBundle.exists() || rnMainBundle.exists()
    ) {
      return true;
    }

    return findBundleFile(bundle) != null;
  }

  private File findBundleFile(final File root) {
    File[] entries = root.listFiles();
    if (entries == null) {
      return null;
    }

    for (File entry : entries) {
      if (
        entry.isFile() &&
        (entry.getName().endsWith(".bundle") ||
          entry.getName().endsWith(".jsbundle"))
      ) {
        return entry;
      }
    }

    for (File entry : entries) {
      if (entry.isDirectory()) {
        File nested = findBundleFile(entry);
        if (nested != null) {
          return nested;
        }
      }
    }

    return null;
  }

  public Boolean set(final BundleInfo bundle) {
    return this.set(bundle.getId());
  }

  public Boolean set(final String id) {
    final BundleInfo newBundle = this.getBundleInfo(id);
    if (newBundle.isBuiltin()) {
      this.reset(true);
      return true;
    }
    Log.i(TAG, "Setting active bundle: " + id);
    if (this.bundleExists(id)) {
      String currentBundleName = this.getCurrentBundle().getVersionName();
      this.setCurrentBundlePath(this.getBundleDirectory(id).getAbsolutePath());
      this.setBundleStatus(id, BundleStatus.PENDING);
      this.sendStats("set", newBundle.getVersionName(), currentBundleName);
      return true;
    } else {
      Log.e(
        TAG,
        "Cannot set active bundle: Bundle " +
        id +
        " does not exist or is invalid."
      );
      this.setBundleStatus(id, BundleStatus.ERROR);
      this.sendStats("set_fail", newBundle.getVersionName());
      return false;
    }
  }

  public void autoReset() {
    final BundleInfo currentBundle = this.getCurrentBundle();
    if (
      !currentBundle.isBuiltin() && !this.bundleExists(currentBundle.getId())
    ) {
      Log.i(TAG, "Folder at bundle path does not exist. Triggering reset.");
      this.reset();
    }
  }

  public void reset() {
    this.reset(false);
  }

  public void reset(final boolean internal) {
    Log.d(TAG, "reset: " + internal);
    var currentBundleName = this.getCurrentBundle().getVersionName();
    this.setCurrentBundlePath("public");
    this.setFallbackBundle(null);
    this.setNextBundle(null);
    if (this.reactContext != null) {
      DownloadWorkerManager.cancelAllDownloads(this.reactContext);
    }
    if (!internal) {
      this.sendStats(
          "reset",
          this.getCurrentBundle().getVersionName(),
          currentBundleName
        );
    }
  }

  public void setSuccess(final BundleInfo bundle, Boolean autoDeletePrevious) {
    this.setBundleStatus(bundle.getId(), BundleStatus.SUCCESS);
    final BundleInfo fallback = this.getFallbackBundle();
    Log.d(ReactNativeUpdaterCore.TAG, "Fallback bundle is: " + fallback);
    Log.i(
      ReactNativeUpdaterCore.TAG,
      "Version successfully loaded: " + bundle.getVersionName()
    );
    if (autoDeletePrevious && !fallback.isBuiltin()) {
      final Boolean res = this.delete(fallback.getId());
      if (res) {
        Log.i(
          ReactNativeUpdaterCore.TAG,
          "Deleted previous bundle: " + fallback.getVersionName()
        );
      }
    }
    this.setFallbackBundle(bundle);
  }

  public void setError(final BundleInfo bundle) {
    this.setBundleStatus(bundle.getId(), BundleStatus.ERROR);
  }

  private JSObject createInfoObject() {
    JSObject json = new JSObject();
    json.put("platform", "android");
    json.put("device_id", this.deviceID);
    json.put("app_id", this.appId);
    json.put("custom_id", this.customId);
    json.put("version_build", this.versionBuild);
    json.put("version_code", this.versionCode);
    json.put("version_os", this.versionOs);
    json.put("version_name", this.getCurrentBundle().getVersionName());
    json.put("plugin_version", this.PLUGIN_VERSION);
    json.put("is_emulator", this.isEmulator());
    json.put("is_prod", this.isProd());
    json.put("defaultChannel", this.defaultChannel);
    return json;
  }

  private void makeJsonRequest(
    String url,
    JSObject jsonBody,
    Callback callback
  ) {
    MediaType JSON = MediaType.get("application/json; charset=utf-8");
    RequestBody body = RequestBody.create(jsonBody.toString(), JSON);

    Request request = new Request.Builder().url(url).post(body).build();

    client
      .newCall(request)
      .enqueue(
        new okhttp3.Callback() {
          @Override
          public void onFailure(@NonNull Call call, @NonNull IOException e) {
            JSObject errorJson = new JSObject();
            errorJson.put("message", "Request failed: " + e.getMessage());
            errorJson.put("error", "network_error");
            callback.callback(errorJson);
          }

          @Override
          public void onResponse(
            @NonNull Call call,
            @NonNull Response response
          ) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (!response.isSuccessful()) {
                JSObject errorJson = new JSObject();
                errorJson.put("message", "Server error: " + response.code());
                errorJson.put("error", "response_error");
                callback.callback(errorJson);
                return;
              }

              assert responseBody != null;
              String responseData = responseBody.string();
              JSONObject jsonResponse = new JSONObject(responseData);
              JSObject ret = new JSObject();

              Iterator<String> keys = jsonResponse.keys();
              while (keys.hasNext()) {
                String key = keys.next();
                if (jsonResponse.has(key)) {
                  if ("session_key".equals(key)) {
                    ret.put("sessionKey", jsonResponse.get(key));
                  } else {
                    ret.put(key, jsonResponse.get(key));
                  }
                }
              }
              callback.callback(ret);
            } catch (JSONException e) {
              JSObject errorJson = new JSObject();
              errorJson.put("message", "JSON parse error: " + e.getMessage());
              errorJson.put("error", "parse_error");
              callback.callback(errorJson);
            }
          }
        }
      );
  }

  public void getLatest(
    final String updateUrl,
    final String channel,
    final Callback callback
  ) {
    JSObject json;
    try {
      json = this.createInfoObject();
      if (channel != null && json != null) {
        json.put("defaultChannel", channel);
      }
    } catch (Exception e) {
      Log.e(TAG, "Error getLatest JSONException", e);
      final JSObject retError = new JSObject();
      retError.put("message", "Cannot get info: " + e);
      retError.put("error", "json_error");
      callback.callback(retError);
      return;
    }

    Log.i(ReactNativeUpdaterCore.TAG, "Auto-update parameters: " + json);

    makeJsonRequest(updateUrl, json, callback);
  }

  public void unsetChannel(
    final SharedPreferences.Editor editor,
    final String defaultChannelKey,
    final String configDefaultChannel,
    final Callback callback
  ) {
    if (editor != null) {
      editor.remove(defaultChannelKey);
      editor.apply();
    }
    this.defaultChannel = configDefaultChannel;
    final JSObject ret = new JSObject();
    ret.put("status", "ok");
    ret.put("message", "Channel override removed");
    callback.callback(ret);
  }

  public void unsetChannel(final Callback callback) {
    unsetChannel(this.editor, "defaultChannel", this.defaultChannel, callback);
  }

  public void setChannel(
    final String channel,
    final SharedPreferences.Editor editor,
    final String defaultChannelKey,
    final String configDefaultChannel,
    final boolean allowSetDefaultChannel,
    final Callback callback
  ) {
    if (!allowSetDefaultChannel) {
      final JSObject retError = new JSObject();
      retError.put("message", "setChannel is disabled by configuration");
      retError.put("error", "disabled_by_config");
      callback.callback(retError);
      return;
    }

    String channelUrl = this.channelUrl;
    if (channelUrl == null || channelUrl.isEmpty()) {
      Log.e(TAG, "Channel URL is not set");
      final JSObject retError = new JSObject();
      retError.put("message", "channelUrl missing");
      retError.put("error", "missing_config");
      callback.callback(retError);
      return;
    }
    JSObject json;
    try {
      json = this.createInfoObject();
      json.put("channel", channel);
    } catch (Exception e) {
      Log.e(TAG, "Error setChannel JSONException", e);
      final JSObject retError = new JSObject();
      retError.put("message", "Cannot get info: " + e);
      retError.put("error", "json_error");
      callback.callback(retError);
      return;
    }

    makeJsonRequest(channelUrl, json, res -> {
      if (res.has("error")) {
        callback.callback(res);
        return;
      }

      if (res.optBoolean("unset", false)) {
        if (editor != null) {
          editor.remove(defaultChannelKey);
          editor.apply();
        }
        this.defaultChannel = configDefaultChannel;
        callback.callback(res);
        return;
      }

      this.defaultChannel = channel;
      if (editor != null) {
        editor.putString(defaultChannelKey, channel);
        editor.apply();
      }
      callback.callback(res);
    });
  }

  public void setChannel(final String channel, final Callback callback) {
    setChannel(
      channel,
      this.editor,
      "defaultChannel",
      this.defaultChannel,
      true,
      callback
    );
  }

  public void getChannel(final Callback callback) {
    String channelUrl = this.channelUrl;
    if (channelUrl == null || channelUrl.isEmpty()) {
      Log.e(TAG, "Channel URL is not set");
      final JSObject retError = new JSObject();
      retError.put("message", "Channel URL is not set");
      retError.put("error", "missing_config");
      callback.callback(retError);
      return;
    }
    JSObject json;
    try {
      json = this.createInfoObject();
    } catch (Exception e) {
      Log.e(TAG, "Error getChannel JSONException", e);
      final JSObject retError = new JSObject();
      retError.put("message", "Cannot get info: " + e);
      retError.put("error", "json_error");
      callback.callback(retError);
      return;
    }

    Request request = new Request.Builder()
      .url(channelUrl)
      .put(
        RequestBody.create(json.toString(), MediaType.get("application/json"))
      )
      .build();

    client
      .newCall(request)
      .enqueue(
        new okhttp3.Callback() {
          @Override
          public void onFailure(@NonNull Call call, @NonNull IOException e) {
            JSObject retError = new JSObject();
            retError.put("message", "Request failed: " + e.getMessage());
            retError.put("error", "network_error");
            callback.callback(retError);
          }

          @Override
          public void onResponse(
            @NonNull Call call,
            @NonNull Response response
          ) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.code() == 400) {
                assert responseBody != null;
                String data = responseBody.string();
                if (
                  data.contains("channel_not_found") &&
                  !defaultChannel.isEmpty()
                ) {
                  JSObject ret = new JSObject();
                  ret.put("channel", defaultChannel);
                  ret.put("status", "default");
                  Log.i(TAG, "Channel get to \"" + ret);
                  callback.callback(ret);
                  return;
                }
              }

              if (!response.isSuccessful()) {
                JSObject retError = new JSObject();
                retError.put("message", "Server error: " + response.code());
                retError.put("error", "response_error");
                callback.callback(retError);
                return;
              }

              assert responseBody != null;
              String responseData = responseBody.string();
              JSONObject jsonResponse = new JSONObject(responseData);
              JSObject ret = new JSObject();

              Iterator<String> keys = jsonResponse.keys();
              while (keys.hasNext()) {
                String key = keys.next();
                if (jsonResponse.has(key)) {
                  ret.put(key, jsonResponse.get(key));
                }
              }
              Log.i(TAG, "Channel get to \"" + ret);
              callback.callback(ret);
            } catch (JSONException e) {
              JSObject retError = new JSObject();
              retError.put("message", "JSON parse error: " + e.getMessage());
              retError.put("error", "parse_error");
              callback.callback(retError);
            }
          }
        }
      );
  }

  public void listChannels(final Callback callback) {
    String channelUrl = this.channelUrl;
    if (channelUrl == null || channelUrl.isEmpty()) {
      Log.e(TAG, "Channel URL is not set");
      final JSObject retError = new JSObject();
      retError.put("message", "Channel URL is not set");
      retError.put("error", "missing_config");
      callback.callback(retError);
      return;
    }

    JSObject json;
    try {
      json = this.createInfoObject();
    } catch (Exception e) {
      Log.e(TAG, "Error listChannels JSONException", e);
      final JSObject retError = new JSObject();
      retError.put("message", "Cannot get info: " + e);
      retError.put("error", "json_error");
      callback.callback(retError);
      return;
    }

    HttpUrl parsed = HttpUrl.parse(channelUrl);
    if (parsed == null) {
      final JSObject retError = new JSObject();
      retError.put("message", "Invalid channel URL");
      retError.put("error", "invalid_url");
      callback.callback(retError);
      return;
    }

    HttpUrl.Builder urlBuilder = parsed.newBuilder();
    Iterator<String> keys = json.keys();
    while (keys.hasNext()) {
      String key = keys.next();
      Object value = json.opt(key);
      if (value != null) {
        urlBuilder.addQueryParameter(key, String.valueOf(value));
      }
    }

    Request request = new Request.Builder()
      .url(urlBuilder.build())
      .get()
      .build();

    client
      .newCall(request)
      .enqueue(
        new okhttp3.Callback() {
          @Override
          public void onFailure(@NonNull Call call, @NonNull IOException e) {
            JSObject retError = new JSObject();
            retError.put("message", "Request failed: " + e.getMessage());
            retError.put("error", "network_error");
            callback.callback(retError);
          }

          @Override
          public void onResponse(
            @NonNull Call call,
            @NonNull Response response
          ) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (!response.isSuccessful()) {
                JSObject retError = new JSObject();
                retError.put("message", "Server error: " + response.code());
                retError.put("error", "response_error");
                callback.callback(retError);
                return;
              }

              if (responseBody == null) {
                JSObject retError = new JSObject();
                retError.put("message", "Empty response body");
                retError.put("error", "response_error");
                callback.callback(retError);
                return;
              }

              String responseData = responseBody.string().trim();
              JSObject ret = new JSObject();

              if (responseData.startsWith("[")) {
                ret.put("channels", new JSONArray(responseData));
                callback.callback(ret);
                return;
              }

              JSONObject jsonResponse = new JSONObject(responseData);
              if (jsonResponse.has("error")) {
                JSObject retError = new JSObject();
                retError.put("error", jsonResponse.optString("error"));
                retError.put(
                  "message",
                  jsonResponse.optString(
                    "message",
                    "server did not provide a message"
                  )
                );
                callback.callback(retError);
                return;
              }

              if (jsonResponse.has("channels")) {
                ret.put("channels", jsonResponse.optJSONArray("channels"));
                callback.callback(ret);
                return;
              }

              ret.put("channels", new JSONArray());
              callback.callback(ret);
            } catch (JSONException e) {
              JSObject retError = new JSObject();
              retError.put("message", "JSON parse error: " + e.getMessage());
              retError.put("error", "parse_error");
              callback.callback(retError);
            }
          }
        }
      );
  }

  public void sendStats(final String action) {
    this.sendStats(action, this.getCurrentBundle().getVersionName());
  }

  public void sendStats(final String action, final String versionName) {
    this.sendStats(action, versionName, "");
  }

  public void sendStats(
    final String action,
    final String versionName,
    final String oldVersionName
  ) {
    String statsUrl = this.statsUrl;
    if (statsUrl == null || statsUrl.isEmpty()) {
      return;
    }
    JSONObject json;
    try {
      json = this.createInfoObject();
      json.put("version_name", versionName);
      json.put("old_version_name", oldVersionName);
      json.put("action", action);
    } catch (JSONException e) {
      Log.e(TAG, "Error sendStats JSONException", e);
      return;
    }

    Request request = new Request.Builder()
      .url(statsUrl)
      .post(
        RequestBody.create(json.toString(), MediaType.get("application/json"))
      )
      .build();

    client
      .newCall(request)
      .enqueue(
        new okhttp3.Callback() {
          @Override
          public void onFailure(@NonNull Call call, @NonNull IOException e) {
            Log.e(TAG, "Failed to send stats: " + e.getMessage());
          }

          @Override
          public void onResponse(
            @NonNull Call call,
            @NonNull Response response
          ) throws IOException {
            if (response.isSuccessful()) {
              Log.i(
                TAG,
                "Stats send for \"" + action + "\", version " + versionName
              );
            } else {
              Log.e(TAG, "Error sending stats: " + response.code());
            }
          }
        }
      );
  }

  public BundleInfo getBundleInfo(final String id) {
    String trueId = BundleInfo.VERSION_UNKNOWN;
    if (id != null) {
      trueId = id;
    }
    BundleInfo result;
    if (BundleInfo.ID_BUILTIN.equals(trueId)) {
      result = new BundleInfo(trueId, null, BundleStatus.SUCCESS, "", "");
    } else if (BundleInfo.VERSION_UNKNOWN.equals(trueId)) {
      result = new BundleInfo(trueId, null, BundleStatus.ERROR, "", "");
    } else {
      try {
        String stored = this.prefs.getString(trueId + INFO_SUFFIX, "");
        result = BundleInfo.fromJSON(stored);
      } catch (JSONException e) {
        Log.e(TAG, "Failed to parse info for bundle [" + trueId + "] ", e);
        result = new BundleInfo(trueId, null, BundleStatus.PENDING, "", "");
      }
    }
    return result;
  }

  public BundleInfo getBundleInfoByName(final String versionName) {
    final List<BundleInfo> installed = this.list(false);
    for (final BundleInfo i : installed) {
      if (i.getVersionName().equals(versionName)) {
        return i;
      }
    }
    return null;
  }

  private void removeBundleInfo(final String id) {
    this.saveBundleInfo(id, null);
  }

  public void saveBundleInfo(final String id, final BundleInfo info) {
    if (
      id == null || (info != null && (info.isBuiltin() || info.isUnknown()))
    ) {
      Log.d(TAG, "Not saving info for bundle: [" + id + "] " + info);
      return;
    }

    if (info == null) {
      Log.d(TAG, "Removing info for bundle [" + id + "]");
      this.editor.remove(id + INFO_SUFFIX);
    } else {
      final BundleInfo update = info.setId(id);
      Log.d(TAG, "Storing info for bundle [" + id + "] " + update.toString());
      this.editor.putString(id + INFO_SUFFIX, update.toString());
    }
    this.editor.commit();
  }

  private void setBundleStatus(final String id, final BundleStatus status) {
    if (id != null && status != null) {
      BundleInfo info = this.getBundleInfo(id);
      Log.d(TAG, "Setting status for bundle [" + id + "] to " + status);
      this.saveBundleInfo(id, info.setStatus(status));
    }
  }

  private String getCurrentBundleId() {
    String path = prefs.getString(
      ReactNativeUpdater.ACTIVE_BUNDLE_PATH_KEY,
      "public"
    );
    if ("public".equals(path)) {
      return BundleInfo.ID_BUILTIN;
    }
    // Extract ID from path
    return path.substring(path.lastIndexOf('/') + 1);
  }

  public BundleInfo getCurrentBundle() {
    return this.getBundleInfo(this.getCurrentBundleId());
  }

  public String getCurrentBundlePath() {
    // Use the custom pref key
    return prefs.getString(ReactNativeUpdater.ACTIVE_BUNDLE_PATH_KEY, "public");
  }

  public Boolean isUsingBuiltin() {
    return "public".equals(this.getCurrentBundlePath());
  }

  public BundleInfo getFallbackBundle() {
    final String id =
      this.prefs.getString(FALLBACK_VERSION, BundleInfo.ID_BUILTIN);
    return this.getBundleInfo(id);
  }

  private void setFallbackBundle(final BundleInfo fallback) {
    this.editor.putString(
        FALLBACK_VERSION,
        fallback == null ? BundleInfo.ID_BUILTIN : fallback.getId()
      );
    this.editor.commit();
  }

  public BundleInfo getNextBundle() {
    final String id = this.prefs.getString(NEXT_VERSION, null);
    if (id == null) return null;
    return this.getBundleInfo(id);
  }

  public boolean setNextBundle(final String next) {
    if (next == null) {
      this.editor.remove(NEXT_VERSION);
    } else {
      final BundleInfo newBundle = this.getBundleInfo(next);
      if (!newBundle.isBuiltin() && !this.bundleExists(next)) {
        return false;
      }
      this.editor.putString(NEXT_VERSION, next);
      this.setBundleStatus(next, BundleStatus.PENDING);
    }
    this.editor.commit();
    return true;
  }

  public String echo(String value) {
    return value;
  }

  public void notifyAppReady() {
    try {
      // This method is called by the MODULE after JS confirms readiness.
      // It should mark the *current* bundle (determined by path pref) as success.
      final BundleInfo bundle = this.getCurrentBundle(); // Gets based on path pref
      if (!bundle.isBuiltin()) {
        this.setSuccess(bundle, true); // Mark current active as success
        // Path pref is the source of truth for current bundle.
        this.editor.commit();
        Log.i(TAG, "Current bundle [" + bundle.getId() + "] marked success.");
      } else {
        Log.i(TAG, "notifyAppReady called for builtin bundle.");
      }
    } catch (final Exception e) {
      Log.e(TAG, "Failed to mark app ready state.", e);
    }
  }

  public int compareVersions(String versionA, String versionB)
    throws IllegalArgumentException {
    Version vA = new Version(versionA);
    Version vB = new Version(versionB);
    if (vA.isHigherThan(vB)) {
      return 1;
    }
    if (vA.isLowerThan(vB)) {
      return -1;
    }
    return 0;
  }

  public void setCurrentBundlePath(String path) {
    this.editor.putString(ReactNativeUpdater.ACTIVE_BUNDLE_PATH_KEY, path);
    this.editor.commit();
  }
}
